name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Playwright
      run: npx playwright install  
 
    - name: Run tests
      run: npm run test

    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report
  
  generateReport:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Download report artifact
      uses: actions/download-artifact@v2
      with:
        name: playwright-report
        path: downloaded-report

    - name: Open Playwright Report
      run: |
          if [ "$(uname)" = "Darwin" ]; then
            open downloaded-report/index.html
          elif [ "$(uname)" = "Linux" ]; then
            if command -v google-chrome; then
              google-chrome downloaded-report/index.html
            elif command -v firefox; then
              firefox downloaded-report/index.html
            else
              echo "Unable to find a supported browser."
              exit 1
            fi
          else
            echo "Unsupported operating system."
            exit 1
          fi