name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Playwright
      run: npx playwright install  
 
    - name: Run tests
      run: npm run test
  
  generateReport:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: $GITHUB_WORKSPACE/playwright-report

    - name: Download report artifact
      uses: actions/download-artifact@v2
      with:
        name: playwright-report
        path: $GITHUB_WORKSPACE/playwright-report

    - name: Open report
      run: 
          open playwright-report/index.html